@echo off
echo Running collection first time...
newman run "C:\Users\Unity_0118\Desktop\Collection_Newman\SIMPLICIALLpostmancollectionNewman.json" -r htmlextra --reporter-htmlextra-export "C:\Users\Unity_0118\Desktop\Collection_Newman\FirstCollectionReport.html"
echo Running collection second time...
newman run "C:\Users\Unity_0118\Desktop\Collection_Newman\SecondCollection.json" -r htmlextra --reporter-htmlextra-export "C:\Users\Unity_0118\Desktop\Collection_Newman\SecondCollectionReport.html"
echo Merging reports...
REM Add your merging logic here
